In [1]:
import pickle

In [8]:
load_model = pickle.load(open('../pickles/pp_pred_pipe', 'rb'))

In [9]:
import pandas as pd
import numpy as np

In [23]:
defaulters = pd.read_csv('/Users/isislim/Documents/LeWagon/defaulter_data_13364.csv')
defaulters.head()

,Unnamed: 0,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,0,6ba461c93869797c49b0f34c29274e50915466eda02a82...,2017-04-29,0.524390,0.331352,0.022647,1.009814,0.009442,0.301375,0.007879,...,NaN,NaN,NaN,1.008062,0.003595,0.874480,0.090184,1.001811,0.004446,0.365380
1,1,6ea315e6f219bc513964121907331f96e5b194127ebee3...,2017-09-10,0.463367,0.003464,0.024714,0.818614,0.504045,0.218091,0.001362,...,0.25245,0.007144,0.0022,0.003997,0.001457,0.009902,NaN,0.003727,0.000199,0.000804
2,2,6f105fec0ab833183a6a7aa3e39e79a6adf88a7cabe9df...,2017-03-26,0.463461,0.093902,0.008374,0.818932,0.501653,0.240602,0.002078,...,NaN,NaN,NaN,0.009838,0.009414,0.006422,NaN,0.004107,0.004965,0.001735
3,3,6f105fec0ab833183a6a7aa3e39e79a6adf88a7cabe9df...,2017-04-26,0.442675,0.002785,0.008545,1.005278,0.008112,0.257985,0.008379,...,NaN,NaN,NaN,0.006977,0.007455,0.001942,NaN,0.006927,0.007293,0.003186
4,4,6f105fec0ab833183a6a7aa3e39e79a6adf88a7cabe9df...,2017-05-26,0.471713,0.095840,0.011414,0.817346,0.508451,0.154248,0.000736,...,NaN,NaN,NaN,0.009866,0.007082,0.002140,NaN,0.005485,0.000920,0.002958

In [24]:
test_row = defaulters.iloc[[0]]
test_row

,Unnamed: 0,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,0,6ba461c93869797c49b0f34c29274e50915466eda02a82...,2017-04-29,0.52439,0.331352,0.022647,1.009814,0.009442,0.301375,0.007879,...,NaN,NaN,NaN,1.008062,0.003595,0.87448,0.090184,1.001811,0.004446,0.36538

In [73]:
load_model.predict(test_row)[0]

1

In [43]:
pred_proba = load_model.predict_proba(test_row)

In [44]:
pred_proba[0][1]

0.6950514069152902

In [28]:
test_row.to_csv('test_row.csv'b)

In [32]:
test_dict = test_row.to_dict(orient='records')[0]
test_dict

{'Unnamed: 0': 0,
 'customer_ID': '6ba461c93869797c49b0f34c29274e50915466eda02a82fde4aa2c73c3924339',
 'S_2': '2017-04-29',
 'P_2': 0.5243904931830153,
 'D_39': 0.3313523183745179,
 'B_1': 0.0226474075652035,
 'B_2': 1.0098138176705274,
 'R_1': 0.0094418612623092,
 'S_3': 0.3013753140016364,
 'D_41': 0.0078785629732383,
 'B_3': 0.0258205059627975,
 'D_42': 0.1442666865165377,
 'D_43': 0.2719021428514478,
 'D_44': nan,
 'B_4': 0.0283137155569896,
 'D_45': 0.0181600179345101,
 'B_5': 0.042604957206283,
 'R_2': 0.0076086225667935,
 'D_46': 0.4423322496494613,
 'D_47': 0.5640947570546344,
 'D_48': nan,
 'D_49': nan,
 'B_6': 0.1141169198300304,
 'B_7': 0.0364595248656915,
 'B_8': 1.001206164416357,
 'D_50': nan,
 'D_51': 0.0055727585123258,
 'B_9': 0.2995098902026097,
 'R_3': 0.5078069824461213,
 'D_52': 0.0065321521685339,
 'P_3': 0.9704147394434446,
 'B_10': 0.1931363807984167,
 'D_53': nan,
 'S_5': 0.0497382032113571,
 'B_11': 0.0170887078387576,
 'S_6': 6.264821241336181e-06,
 'D_54': 1.003239737456082,
 'R_4': 0.0097192267864564,
 'S_7': 0.5836650003043637,
 'B_12': 0.0279422840289572,
 'S_8': 0.4724606934230521,
 'D_55': 0.3718658693500563,
 'D_56': nan,
 'B_13': 0.0229769009343403,
 'R_5': 0.0024600658719739,
 'D_58': 0.092685414392393,
 'S_9': nan,
 'B_14': 0.0187415315595689,
 'D_59': 0.2725730447049424,
 'D_60': 0.5128522688445263,
 'D_61': 0.996966160590678,
 'B_15': 0.008916801024969,
 'S_11': 0.2839718258314885,
 'D_62': 0.0063765535043084,
 'D_63': 'CO',
 'D_64': 'U',
 'D_65': 0.0082769054925904,
 'B_16': 0.3406488182369175,
 'B_17': 0.009998703087497,
 'B_18': 0.6902283738451007,
 'B_19': 0.0081695078433936,
 'D_66': nan,
 'B_20': 0.0006330919917411,
 'D_68': 3.0,
 'S_12': 0.1916605915252538,
 'R_6': 0.0080456630109759,
 'S_13': 0.0018278306292617,
 'B_21': 0.0013618570248982,
 'D_69': 0.0985397767929114,
 'B_22': 0.0072234345795886,
 'D_70': 0.0090138733828583,
 'D_71': 0.0069688305279365,
 'D_72': 0.341570684555522,
 'S_15': 0.2066711654452798,
 'B_23': 0.0211564693339486,
 'D_73': nan,
 'P_4': 0.9268010960381086,
 'D_74': 0.0806280135617195,
 'D_75': 0.0729107856856167,
 'D_76': nan,
 'B_24': 0.0007743527406967,
 'R_7': 0.0036305356399982,
 'D_77': nan,
 'B_25': 0.0269237456259648,
 'B_26': 0.0020041265394678,
 'D_78': nan,
 'D_79': 0.0019684030320729,
 'R_8': 0.0095986871190017,
 'R_9': nan,
 'S_16': 0.0073472057447631,
 'D_80': 0.0046132681510072,
 'R_10': 0.0002366237215068,
 'R_11': 0.5030766236950268,
 'B_27': 0.0080865243484111,
 'D_81': 0.0016620748567789,
 'D_82': nan,
 'S_17': 0.0080248355218849,
 'R_12': 1.0088355475409474,
 'B_28': 0.0174737864388395,
 'R_13': 0.005137948786245,
 'D_83': 1.0010212222511732,
 'R_14': 0.0097658691950037,
 'R_15': 0.007744656789712,
 'D_84': 0.0053338538809249,
 'R_16': 0.5068937771309112,
 'B_29': nan,
 'B_30': 0.0,
 'S_18': 0.0025881480646735,
 'D_86': 0.0084592043500856,
 'D_87': nan,
 'R_17': 0.0064107803599046,
 'R_18': 0.0021582068627253,
 'D_88': nan,
 'B_31': 1,
 'S_19': 0.0036599241820819,
 'R_19': 0.0023951620876795,
 'B_32': 0.0058979996465047,
 'S_20': 0.0084387973217704,
 'R_20': 0.0072765937081887,
 'R_21': 0.0026307474714683,
 'B_33': 1.0042078645998118,
 'D_89': 0.0093799559198365,
 'R_22': 0.0032245356122126,
 'R_23': 0.0084210175139439,
 'D_91': 0.0021117280992512,
 'D_92': 0.0002813886044537,
 'D_93': 0.0064740428785274,
 'D_94': 0.0034891282055373,
 'R_24': 0.0074637673580497,
 'R_25': 8.514154457408552e-05,
 'D_96': 0.0022346601508937,
 'S_22': 0.9896390752145902,
 'S_23': 0.1321254122831956,
 'S_24': 0.9834439806950838,
 'S_25': 0.9738907537358952,
 'S_26': 0.0038862860431581,
 'D_102': 0.289217832863587,
 'D_103': 1.0056231504565114,
 'D_104': 0.9613147105437548,
 'D_105': 0.1697762859187989,
 'D_106': nan,
 'D_107': 0.3415914097814573,
 'B_36': 0.0014437035216303,
 'B_37': 0.0269399028855463,
 'R_26': 0.1079921756486303,
 'R_27': 0.0102809017375042,
 'B_38': 2.0,
 'D_108': nan,
 'D_109': 0.0045981590747289,
 'D_110': nan,
 'D_111': nan,
 'B_39': nan,
 'D_112': 0.0126469786018308,
 'B_40': 0.111658105064575,
 'S_27': 0.0085330483574145,
 'D_113': 0.6060588458397328,
 'D_114': 0.0,
 'D_115': 0.0543636921559064,
 'D_116': 0.0,
 'D_117': 3.0,
 'D_118': 0.1168077296764655,
 'D_119': 0.1096212138082288,
 'D_120': 0.0,
 'D_121': 0.650981600072707,
 'D_122': 0.146803227388556,
 'D_123': 0.0011049696432874,
 'D_124': 0.8183435054999706,
 'D_125': 0.000647677346751,
 'D_126': 1.0,
 'D_127': 5.266267486242482e-06,
 'D_128': 0.0029830598258818,
 'D_129': 0.007395236340952,
 'B_41': 0.0031757932139252,
 'B_42': nan,
 'D_130': 1.0020848849400965,
 'D_131': 0.0061371572650052,
 'D_132': nan,
 'D_133': 0.0018016269009619,
 'R_28': 0.0021418392238124,
 'D_134': nan,
 'D_135': nan,
 'D_136': nan,
 'D_137': nan,
 'D_138': nan,
 'D_139': 1.0080621413676547,
 'D_140': 0.0035948604672395,
 'D_141': 0.8744796412184572,
 'D_142': 0.0901836791309312,
 'D_143': 1.0018106904900153,
 'D_144': 0.0044457500675465,
 'D_145': 0.3653796067325561}

In [42]:
new_array = pd.DataFrame.from_dict(test_dict,orient='index').transpose()
new_array

,Unnamed: 0,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,0,6ba461c93869797c49b0f34c29274e50915466eda02a82...,2017-04-29,0.52439,0.331352,0.022647,1.009814,0.009442,0.301375,0.007879,...,NaN,NaN,NaN,1.008062,0.003595,0.87448,0.090184,1.001811,0.004446,0.36538

In [45]:
import requests

In [75]:
test = pd.read_csv('../AMEX_default_prediction/api/test_row.csv',index_col=0)
test

,Unnamed: 0,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,0,6ba461c93869797c49b0f34c29274e50915466eda02a82...,2017-04-29,0.52439,0.331352,0.022647,1.009814,0.009442,0.301375,0.007879,...,NaN,NaN,NaN,1.008062,0.003595,0.87448,0.090184,1.001811,0.004446,0.36538

In [76]:
test

,Unnamed: 0,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,0,6ba461c93869797c49b0f34c29274e50915466eda02a82...,2017-04-29,0.52439,0.331352,0.022647,1.009814,0.009442,0.301375,0.007879,...,NaN,NaN,NaN,1.008062,0.003595,0.87448,0.090184,1.001811,0.004446,0.36538

In [59]:
url = 'http://localhost:8000/predict'
params = pd.read_csv('../AMEX_default_prediction/api/test_row.csv').to_dict(orient='records')[0]
response = requests.get(url, params=params)
response.json()

{'detail': [{'loc': ['query', 'params'],
   'msg': 'field required',
   'type': 'value_error.missing'}]}

In [102]:
params = pd.read_csv('../AMEX_default_prediction/api/test_row.csv').fillna('').to_dict(orient='records')[0]
params

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0,
 'customer_ID': '6ba461c93869797c49b0f34c29274e50915466eda02a82fde4aa2c73c3924339',
 'S_2': '2017-04-29',
 'P_2': 0.5243904931830153,
 'D_39': 0.3313523183745179,
 'B_1': 0.0226474075652035,
 'B_2': 1.0098138176705274,
 'R_1': 0.0094418612623092,
 'S_3': 0.3013753140016364,
 'D_41': 0.0078785629732383,
 'B_3': 0.0258205059627975,
 'D_42': 0.1442666865165377,
 'D_43': 0.2719021428514478,
 'D_44': '',
 'B_4': 0.0283137155569896,
 'D_45': 0.0181600179345101,
 'B_5': 0.042604957206283,
 'R_2': 0.0076086225667935,
 'D_46': 0.4423322496494613,
 'D_47': 0.5640947570546344,
 'D_48': '',
 'D_49': '',
 'B_6': 0.1141169198300304,
 'B_7': 0.0364595248656915,
 'B_8': 1.001206164416357,
 'D_50': '',
 'D_51': 0.0055727585123258,
 'B_9': 0.2995098902026097,
 'R_3': 0.5078069824461213,
 'D_52': 0.0065321521685339,
 'P_3': 0.9704147394434446,
 'B_10': 0.1931363807984167,
 'D_53': '',
 'S_5': 0.0497382032113571,
 'B_11': 0.0170887078387576,
 'S_6': 6.264821241336181e-06,
 'D_54': 1.003239737456082,
 'R_4': 0.0097192267864564,
 'S_7': 0.5836650003043637,
 'B_12': 0.0279422840289572,
 'S_8': 0.4724606934230521,
 'D_55': 0.3718658693500563,
 'D_56': '',
 'B_13': 0.0229769009343403,
 'R_5': 0.0024600658719739,
 'D_58': 0.092685414392393,
 'S_9': '',
 'B_14': 0.0187415315595689,
 'D_59': 0.2725730447049424,
 'D_60': 0.5128522688445263,
 'D_61': 0.996966160590678,
 'B_15': 0.008916801024969,
 'S_11': 0.2839718258314885,
 'D_62': 0.0063765535043084,
 'D_63': 'CO',
 'D_64': 'U',
 'D_65': 0.0082769054925904,
 'B_16': 0.3406488182369175,
 'B_17': 0.009998703087497,
 'B_18': 0.6902283738451007,
 'B_19': 0.0081695078433936,
 'D_66': '',
 'B_20': 0.0006330919917411,
 'D_68': 3.0,
 'S_12': 0.1916605915252538,
 'R_6': 0.0080456630109759,
 'S_13': 0.0018278306292617,
 'B_21': 0.0013618570248982,
 'D_69': 0.0985397767929114,
 'B_22': 0.0072234345795886,
 'D_70': 0.0090138733828583,
 'D_71': 0.0069688305279365,
 'D_72': 0.341570684555522,
 'S_15': 0.2066711654452798,
 'B_23': 0.0211564693339486,
 'D_73': '',
 'P_4': 0.9268010960381086,
 'D_74': 0.0806280135617195,
 'D_75': 0.0729107856856167,
 'D_76': '',
 'B_24': 0.0007743527406967,
 'R_7': 0.0036305356399982,
 'D_77': '',
 'B_25': 0.0269237456259648,
 'B_26': 0.0020041265394678,
 'D_78': '',
 'D_79': 0.0019684030320729,
 'R_8': 0.0095986871190017,
 'R_9': '',
 'S_16': 0.0073472057447631,
 'D_80': 0.0046132681510072,
 'R_10': 0.0002366237215068,
 'R_11': 0.5030766236950268,
 'B_27': 0.0080865243484111,
 'D_81': 0.0016620748567789,
 'D_82': '',
 'S_17': 0.0080248355218849,
 'R_12': 1.0088355475409474,
 'B_28': 0.0174737864388395,
 'R_13': 0.005137948786245,
 'D_83': 1.0010212222511732,
 'R_14': 0.0097658691950037,
 'R_15': 0.007744656789712,
 'D_84': 0.0053338538809249,
 'R_16': 0.5068937771309112,
 'B_29': '',
 'B_30': 0.0,
 'S_18': 0.0025881480646735,
 'D_86': 0.0084592043500856,
 'D_87': '',
 'R_17': 0.0064107803599046,
 'R_18': 0.0021582068627253,
 'D_88': '',
 'B_31': 1,
 'S_19': 0.0036599241820819,
 'R_19': 0.0023951620876795,
 'B_32': 0.0058979996465047,
 'S_20': 0.0084387973217704,
 'R_20': 0.0072765937081887,
 'R_21': 0.0026307474714683,
 'B_33': 1.0042078645998118,
 'D_89': 0.0093799559198365,
 'R_22': 0.0032245356122126,
 'R_23': 0.0084210175139439,
 'D_91': 0.0021117280992512,
 'D_92': 0.0002813886044537,
 'D_93': 0.0064740428785274,
 'D_94': 0.0034891282055373,
 'R_24': 0.0074637673580497,
 'R_25': 8.514154457408552e-05,
 'D_96': 0.0022346601508937,
 'S_22': 0.9896390752145902,
 'S_23': 0.1321254122831956,
 'S_24': 0.9834439806950838,
 'S_25': 0.9738907537358952,
 'S_26': 0.0038862860431581,
 'D_102': 0.289217832863587,
 'D_103': 1.0056231504565114,
 'D_104': 0.9613147105437548,
 'D_105': 0.1697762859187989,
 'D_106': '',
 'D_107': 0.3415914097814573,
 'B_36': 0.0014437035216303,
 'B_37': 0.0269399028855463,
 'R_26': 0.1079921756486303,
 'R_27': 0.0102809017375042,
 'B_38': 2.0,
 'D_108': '',
 'D_109': 0.0045981590747289,
 'D_110': '',
 'D_111': '',
 'B_39': '',
 'D_112': 0.0126469786018308,
 'B_40': 0.111658105064575,
 'S_27': 0.0085330483574145,
 'D_113': 0.6060588458397328,
 'D_114': 0.0,
 'D_115': 0.0543636921559064,
 'D_116': 0.0,
 'D_117': 3.0,
 'D_118': 0.1168077296764655,
 'D_119': 0.1096212138082288,
 'D_120': 0.0,
 'D_121': 0.650981600072707,
 'D_122': 0.146803227388556,
 'D_123': 0.0011049696432874,
 'D_124': 0.8183435054999706,
 'D_125': 0.000647677346751,
 'D_126': 1.0,
 'D_127': 5.266267486242482e-06,
 'D_128': 0.0029830598258818,
 'D_129': 0.007395236340952,
 'B_41': 0.0031757932139252,
 'B_42': '',
 'D_130': 1.0020848849400965,
 'D_131': 0.0061371572650052,
 'D_132': '',
 'D_133': 0.0018016269009619,
 'R_28': 0.0021418392238124,
 'D_134': '',
 'D_135': '',
 'D_136': '',
 'D_137': '',
 'D_138': '',
 'D_139': 1.0080621413676547,
 'D_140': 0.0035948604672395,
 'D_141': 0.8744796412184572,
 'D_142': 0.0901836791309312,
 'D_143': 1.0018106904900153,
 'D_144': 0.0044457500675465,
 'D_145': 0.3653796067325561}

In [71]:
url = 'http://localhost:8000/predict'
params = test.to_dict(orient='records')[0]
response = requests.get(url, params=params)
response.json()

{'detail': [{'loc': ['query', 'params'],
   'msg': 'field required',
   'type': 'value_error.missing'}]}

In [91]:
params = test.to_dict(orient='records')[0]

In [92]:
params

{'Unnamed: 0': 0,
 'customer_ID': '6ba461c93869797c49b0f34c29274e50915466eda02a82fde4aa2c73c3924339',
 'S_2': '2017-04-29',
 'P_2': 0.5243904931830153,
 'D_39': 0.3313523183745179,
 'B_1': 0.0226474075652035,
 'B_2': 1.0098138176705274,
 'R_1': 0.0094418612623092,
 'S_3': 0.3013753140016364,
 'D_41': 0.0078785629732383,
 'B_3': 0.0258205059627975,
 'D_42': 0.1442666865165377,
 'D_43': 0.2719021428514478,
 'D_44': nan,
 'B_4': 0.0283137155569896,
 'D_45': 0.0181600179345101,
 'B_5': 0.042604957206283,
 'R_2': 0.0076086225667935,
 'D_46': 0.4423322496494613,
 'D_47': 0.5640947570546344,
 'D_48': nan,
 'D_49': nan,
 'B_6': 0.1141169198300304,
 'B_7': 0.0364595248656915,
 'B_8': 1.001206164416357,
 'D_50': nan,
 'D_51': 0.0055727585123258,
 'B_9': 0.2995098902026097,
 'R_3': 0.5078069824461213,
 'D_52': 0.0065321521685339,
 'P_3': 0.9704147394434446,
 'B_10': 0.1931363807984167,
 'D_53': nan,
 'S_5': 0.0497382032113571,
 'B_11': 0.0170887078387576,
 'S_6': 6.264821241336181e-06,
 'D_54': 1.003239737456082,
 'R_4': 0.0097192267864564,
 'S_7': 0.5836650003043637,
 'B_12': 0.0279422840289572,
 'S_8': 0.4724606934230521,
 'D_55': 0.3718658693500563,
 'D_56': nan,
 'B_13': 0.0229769009343403,
 'R_5': 0.0024600658719739,
 'D_58': 0.092685414392393,
 'S_9': nan,
 'B_14': 0.0187415315595689,
 'D_59': 0.2725730447049424,
 'D_60': 0.5128522688445263,
 'D_61': 0.996966160590678,
 'B_15': 0.008916801024969,
 'S_11': 0.2839718258314885,
 'D_62': 0.0063765535043084,
 'D_63': 'CO',
 'D_64': 'U',
 'D_65': 0.0082769054925904,
 'B_16': 0.3406488182369175,
 'B_17': 0.009998703087497,
 'B_18': 0.6902283738451007,
 'B_19': 0.0081695078433936,
 'D_66': nan,
 'B_20': 0.0006330919917411,
 'D_68': 3.0,
 'S_12': 0.1916605915252538,
 'R_6': 0.0080456630109759,
 'S_13': 0.0018278306292617,
 'B_21': 0.0013618570248982,
 'D_69': 0.0985397767929114,
 'B_22': 0.0072234345795886,
 'D_70': 0.0090138733828583,
 'D_71': 0.0069688305279365,
 'D_72': 0.341570684555522,
 'S_15': 0.2066711654452798,
 'B_23': 0.0211564693339486,
 'D_73': nan,
 'P_4': 0.9268010960381086,
 'D_74': 0.0806280135617195,
 'D_75': 0.0729107856856167,
 'D_76': nan,
 'B_24': 0.0007743527406967,
 'R_7': 0.0036305356399982,
 'D_77': nan,
 'B_25': 0.0269237456259648,
 'B_26': 0.0020041265394678,
 'D_78': nan,
 'D_79': 0.0019684030320729,
 'R_8': 0.0095986871190017,
 'R_9': nan,
 'S_16': 0.0073472057447631,
 'D_80': 0.0046132681510072,
 'R_10': 0.0002366237215068,
 'R_11': 0.5030766236950268,
 'B_27': 0.0080865243484111,
 'D_81': 0.0016620748567789,
 'D_82': nan,
 'S_17': 0.0080248355218849,
 'R_12': 1.0088355475409474,
 'B_28': 0.0174737864388395,
 'R_13': 0.005137948786245,
 'D_83': 1.0010212222511732,
 'R_14': 0.0097658691950037,
 'R_15': 0.007744656789712,
 'D_84': 0.0053338538809249,
 'R_16': 0.5068937771309112,
 'B_29': nan,
 'B_30': 0.0,
 'S_18': 0.0025881480646735,
 'D_86': 0.0084592043500856,
 'D_87': nan,
 'R_17': 0.0064107803599046,
 'R_18': 0.0021582068627253,
 'D_88': nan,
 'B_31': 1,
 'S_19': 0.0036599241820819,
 'R_19': 0.0023951620876795,
 'B_32': 0.0058979996465047,
 'S_20': 0.0084387973217704,
 'R_20': 0.0072765937081887,
 'R_21': 0.0026307474714683,
 'B_33': 1.0042078645998118,
 'D_89': 0.0093799559198365,
 'R_22': 0.0032245356122126,
 'R_23': 0.0084210175139439,
 'D_91': 0.0021117280992512,
 'D_92': 0.0002813886044537,
 'D_93': 0.0064740428785274,
 'D_94': 0.0034891282055373,
 'R_24': 0.0074637673580497,
 'R_25': 8.514154457408552e-05,
 'D_96': 0.0022346601508937,
 'S_22': 0.9896390752145902,
 'S_23': 0.1321254122831956,
 'S_24': 0.9834439806950838,
 'S_25': 0.9738907537358952,
 'S_26': 0.0038862860431581,
 'D_102': 0.289217832863587,
 'D_103': 1.0056231504565114,
 'D_104': 0.9613147105437548,
 'D_105': 0.1697762859187989,
 'D_106': nan,
 'D_107': 0.3415914097814573,
 'B_36': 0.0014437035216303,
 'B_37': 0.0269399028855463,
 'R_26': 0.1079921756486303,
 'R_27': 0.0102809017375042,
 'B_38': 2.0,
 'D_108': nan,
 'D_109': 0.0045981590747289,
 'D_110': nan,
 'D_111': nan,
 'B_39': nan,
 'D_112': 0.0126469786018308,
 'B_40': 0.111658105064575,
 'S_27': 0.0085330483574145,
 'D_113': 0.6060588458397328,
 'D_114': 0.0,
 'D_115': 0.0543636921559064,
 'D_116': 0.0,
 'D_117': 3.0,
 'D_118': 0.1168077296764655,
 'D_119': 0.1096212138082288,
 'D_120': 0.0,
 'D_121': 0.650981600072707,
 'D_122': 0.146803227388556,
 'D_123': 0.0011049696432874,
 'D_124': 0.8183435054999706,
 'D_125': 0.000647677346751,
 'D_126': 1.0,
 'D_127': 5.266267486242482e-06,
 'D_128': 0.0029830598258818,
 'D_129': 0.007395236340952,
 'B_41': 0.0031757932139252,
 'B_42': nan,
 'D_130': 1.0020848849400965,
 'D_131': 0.0061371572650052,
 'D_132': nan,
 'D_133': 0.0018016269009619,
 'R_28': 0.0021418392238124,
 'D_134': nan,
 'D_135': nan,
 'D_136': nan,
 'D_137': nan,
 'D_138': nan,
 'D_139': 1.0080621413676547,
 'D_140': 0.0035948604672395,
 'D_141': 0.8744796412184572,
 'D_142': 0.0901836791309312,
 'D_143': 1.0018106904900153,
 'D_144': 0.0044457500675465,
 'D_145': 0.3653796067325561}

In [106]:
X_pred = pd.DataFrame.from_dict(params, orient="index").transpose().replace('',np.nan)

In [107]:
X_pred

,Unnamed: 0.1,Unnamed: 0,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,0,0,6ba461c93869797c49b0f34c29274e50915466eda02a82...,2017-04-29,0.52439,0.331352,0.022647,1.009814,0.009442,0.301375,...,NaN,NaN,NaN,1.008062,0.003595,0.87448,0.090184,1.001811,0.004446,0.36538

In [99]:
X_pred.fillna('')

,Unnamed: 0,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,0,6ba461c93869797c49b0f34c29274e50915466eda02a82...,2017-04-29,0.52439,0.331352,0.022647,1.009814,0.009442,0.301375,0.007879,...,,,,1.008062,0.003595,0.87448,0.090184,1.001811,0.004446,0.36538

In [109]:
data2 = pd.read_csv('../AMEX_default_prediction/api/test_row.csv',index_col=0).fillna('').to_dict(orient='records')[0]
data2

{'Unnamed: 0': 0,
 'customer_ID': '6ba461c93869797c49b0f34c29274e50915466eda02a82fde4aa2c73c3924339',
 'S_2': '2017-04-29',
 'P_2': 0.5243904931830153,
 'D_39': 0.3313523183745179,
 'B_1': 0.0226474075652035,
 'B_2': 1.0098138176705274,
 'R_1': 0.0094418612623092,
 'S_3': 0.3013753140016364,
 'D_41': 0.0078785629732383,
 'B_3': 0.0258205059627975,
 'D_42': 0.1442666865165377,
 'D_43': 0.2719021428514478,
 'D_44': '',
 'B_4': 0.0283137155569896,
 'D_45': 0.0181600179345101,
 'B_5': 0.042604957206283,
 'R_2': 0.0076086225667935,
 'D_46': 0.4423322496494613,
 'D_47': 0.5640947570546344,
 'D_48': '',
 'D_49': '',
 'B_6': 0.1141169198300304,
 'B_7': 0.0364595248656915,
 'B_8': 1.001206164416357,
 'D_50': '',
 'D_51': 0.0055727585123258,
 'B_9': 0.2995098902026097,
 'R_3': 0.5078069824461213,
 'D_52': 0.0065321521685339,
 'P_3': 0.9704147394434446,
 'B_10': 0.1931363807984167,
 'D_53': '',
 'S_5': 0.0497382032113571,
 'B_11': 0.0170887078387576,
 'S_6': 6.264821241336181e-06,
 'D_54': 1.003239737456082,
 'R_4': 0.0097192267864564,
 'S_7': 0.5836650003043637,
 'B_12': 0.0279422840289572,
 'S_8': 0.4724606934230521,
 'D_55': 0.3718658693500563,
 'D_56': '',
 'B_13': 0.0229769009343403,
 'R_5': 0.0024600658719739,
 'D_58': 0.092685414392393,
 'S_9': '',
 'B_14': 0.0187415315595689,
 'D_59': 0.2725730447049424,
 'D_60': 0.5128522688445263,
 'D_61': 0.996966160590678,
 'B_15': 0.008916801024969,
 'S_11': 0.2839718258314885,
 'D_62': 0.0063765535043084,
 'D_63': 'CO',
 'D_64': 'U',
 'D_65': 0.0082769054925904,
 'B_16': 0.3406488182369175,
 'B_17': 0.009998703087497,
 'B_18': 0.6902283738451007,
 'B_19': 0.0081695078433936,
 'D_66': '',
 'B_20': 0.0006330919917411,
 'D_68': 3.0,
 'S_12': 0.1916605915252538,
 'R_6': 0.0080456630109759,
 'S_13': 0.0018278306292617,
 'B_21': 0.0013618570248982,
 'D_69': 0.0985397767929114,
 'B_22': 0.0072234345795886,
 'D_70': 0.0090138733828583,
 'D_71': 0.0069688305279365,
 'D_72': 0.341570684555522,
 'S_15': 0.2066711654452798,
 'B_23': 0.0211564693339486,
 'D_73': '',
 'P_4': 0.9268010960381086,
 'D_74': 0.0806280135617195,
 'D_75': 0.0729107856856167,
 'D_76': '',
 'B_24': 0.0007743527406967,
 'R_7': 0.0036305356399982,
 'D_77': '',
 'B_25': 0.0269237456259648,
 'B_26': 0.0020041265394678,
 'D_78': '',
 'D_79': 0.0019684030320729,
 'R_8': 0.0095986871190017,
 'R_9': '',
 'S_16': 0.0073472057447631,
 'D_80': 0.0046132681510072,
 'R_10': 0.0002366237215068,
 'R_11': 0.5030766236950268,
 'B_27': 0.0080865243484111,
 'D_81': 0.0016620748567789,
 'D_82': '',
 'S_17': 0.0080248355218849,
 'R_12': 1.0088355475409474,
 'B_28': 0.0174737864388395,
 'R_13': 0.005137948786245,
 'D_83': 1.0010212222511732,
 'R_14': 0.0097658691950037,
 'R_15': 0.007744656789712,
 'D_84': 0.0053338538809249,
 'R_16': 0.5068937771309112,
 'B_29': '',
 'B_30': 0.0,
 'S_18': 0.0025881480646735,
 'D_86': 0.0084592043500856,
 'D_87': '',
 'R_17': 0.0064107803599046,
 'R_18': 0.0021582068627253,
 'D_88': '',
 'B_31': 1,
 'S_19': 0.0036599241820819,
 'R_19': 0.0023951620876795,
 'B_32': 0.0058979996465047,
 'S_20': 0.0084387973217704,
 'R_20': 0.0072765937081887,
 'R_21': 0.0026307474714683,
 'B_33': 1.0042078645998118,
 'D_89': 0.0093799559198365,
 'R_22': 0.0032245356122126,
 'R_23': 0.0084210175139439,
 'D_91': 0.0021117280992512,
 'D_92': 0.0002813886044537,
 'D_93': 0.0064740428785274,
 'D_94': 0.0034891282055373,
 'R_24': 0.0074637673580497,
 'R_25': 8.514154457408552e-05,
 'D_96': 0.0022346601508937,
 'S_22': 0.9896390752145902,
 'S_23': 0.1321254122831956,
 'S_24': 0.9834439806950838,
 'S_25': 0.9738907537358952,
 'S_26': 0.0038862860431581,
 'D_102': 0.289217832863587,
 'D_103': 1.0056231504565114,
 'D_104': 0.9613147105437548,
 'D_105': 0.1697762859187989,
 'D_106': '',
 'D_107': 0.3415914097814573,
 'B_36': 0.0014437035216303,
 'B_37': 0.0269399028855463,
 'R_26': 0.1079921756486303,
 'R_27': 0.0102809017375042,
 'B_38': 2.0,
 'D_108': '',
 'D_109': 0.0045981590747289,
 'D_110': '',
 'D_111': '',
 'B_39': '',
 'D_112': 0.0126469786018308,
 'B_40': 0.111658105064575,
 'S_27': 0.0085330483574145,
 'D_113': 0.6060588458397328,
 'D_114': 0.0,
 'D_115': 0.0543636921559064,
 'D_116': 0.0,
 'D_117': 3.0,
 'D_118': 0.1168077296764655,
 'D_119': 0.1096212138082288,
 'D_120': 0.0,
 'D_121': 0.650981600072707,
 'D_122': 0.146803227388556,
 'D_123': 0.0011049696432874,
 'D_124': 0.8183435054999706,
 'D_125': 0.000647677346751,
 'D_126': 1.0,
 'D_127': 5.266267486242482e-06,
 'D_128': 0.0029830598258818,
 'D_129': 0.007395236340952,
 'B_41': 0.0031757932139252,
 'B_42': '',
 'D_130': 1.0020848849400965,
 'D_131': 0.0061371572650052,
 'D_132': '',
 'D_133': 0.0018016269009619,
 'R_28': 0.0021418392238124,
 'D_134': '',
 'D_135': '',
 'D_136': '',
 'D_137': '',
 'D_138': '',
 'D_139': 1.0080621413676547,
 'D_140': 0.0035948604672395,
 'D_141': 0.8744796412184572,
 'D_142': 0.0901836791309312,
 'D_143': 1.0018106904900153,
 'D_144': 0.0044457500675465,
 'D_145': 0.3653796067325561}

In [110]:
import json

In [112]:
params = {"data": json.dumps(data2)}
params

{'data': '{"Unnamed: 0": 0, "customer_ID": "6ba461c93869797c49b0f34c29274e50915466eda02a82fde4aa2c73c3924339", "S_2": "2017-04-29", "P_2": 0.5243904931830153, "D_39": 0.3313523183745179, "B_1": 0.0226474075652035, "B_2": 1.0098138176705274, "R_1": 0.0094418612623092, "S_3": 0.3013753140016364, "D_41": 0.0078785629732383, "B_3": 0.0258205059627975, "D_42": 0.1442666865165377, "D_43": 0.2719021428514478, "D_44": "", "B_4": 0.0283137155569896, "D_45": 0.0181600179345101, "B_5": 0.042604957206283, "R_2": 0.0076086225667935, "D_46": 0.4423322496494613, "D_47": 0.5640947570546344, "D_48": "", "D_49": "", "B_6": 0.1141169198300304, "B_7": 0.0364595248656915, "B_8": 1.001206164416357, "D_50": "", "D_51": 0.0055727585123258, "B_9": 0.2995098902026097, "R_3": 0.5078069824461213, "D_52": 0.0065321521685339, "P_3": 0.9704147394434446, "B_10": 0.1931363807984167, "D_53": "", "S_5": 0.0497382032113571, "B_11": 0.0170887078387576, "S_6": 6.264821241336181e-06, "D_54": 1.003239737456082, "R_4": 0.0097192267864564, "S_7": 0.5836650003043637, "B_12": 0.0279422840289572, "S_8": 0.4724606934230521, "D_55": 0.3718658693500563, "D_56": "", "B_13": 0.0229769009343403, "R_5": 0.0024600658719739, "D_58": 0.092685414392393, "S_9": "", "B_14": 0.0187415315595689, "D_59": 0.2725730447049424, "D_60": 0.5128522688445263, "D_61": 0.996966160590678, "B_15": 0.008916801024969, "S_11": 0.2839718258314885, "D_62": 0.0063765535043084, "D_63": "CO", "D_64": "U", "D_65": 0.0082769054925904, "B_16": 0.3406488182369175, "B_17": 0.009998703087497, "B_18": 0.6902283738451007, "B_19": 0.0081695078433936, "D_66": "", "B_20": 0.0006330919917411, "D_68": 3.0, "S_12": 0.1916605915252538, "R_6": 0.0080456630109759, "S_13": 0.0018278306292617, "B_21": 0.0013618570248982, "D_69": 0.0985397767929114, "B_22": 0.0072234345795886, "D_70": 0.0090138733828583, "D_71": 0.0069688305279365, "D_72": 0.341570684555522, "S_15": 0.2066711654452798, "B_23": 0.0211564693339486, "D_73": "", "P_4": 0.9268010960381086, "D_74": 0.0806280135617195, "D_75": 0.0729107856856167, "D_76": "", "B_24": 0.0007743527406967, "R_7": 0.0036305356399982, "D_77": "", "B_25": 0.0269237456259648, "B_26": 0.0020041265394678, "D_78": "", "D_79": 0.0019684030320729, "R_8": 0.0095986871190017, "R_9": "", "S_16": 0.0073472057447631, "D_80": 0.0046132681510072, "R_10": 0.0002366237215068, "R_11": 0.5030766236950268, "B_27": 0.0080865243484111, "D_81": 0.0016620748567789, "D_82": "", "S_17": 0.0080248355218849, "R_12": 1.0088355475409474, "B_28": 0.0174737864388395, "R_13": 0.005137948786245, "D_83": 1.0010212222511732, "R_14": 0.0097658691950037, "R_15": 0.007744656789712, "D_84": 0.0053338538809249, "R_16": 0.5068937771309112, "B_29": "", "B_30": 0.0, "S_18": 0.0025881480646735, "D_86": 0.0084592043500856, "D_87": "", "R_17": 0.0064107803599046, "R_18": 0.0021582068627253, "D_88": "", "B_31": 1, "S_19": 0.0036599241820819, "R_19": 0.0023951620876795, "B_32": 0.0058979996465047, "S_20": 0.0084387973217704, "R_20": 0.0072765937081887, "R_21": 0.0026307474714683, "B_33": 1.0042078645998118, "D_89": 0.0093799559198365, "R_22": 0.0032245356122126, "R_23": 0.0084210175139439, "D_91": 0.0021117280992512, "D_92": 0.0002813886044537, "D_93": 0.0064740428785274, "D_94": 0.0034891282055373, "R_24": 0.0074637673580497, "R_25": 8.514154457408552e-05, "D_96": 0.0022346601508937, "S_22": 0.9896390752145902, "S_23": 0.1321254122831956, "S_24": 0.9834439806950838, "S_25": 0.9738907537358952, "S_26": 0.0038862860431581, "D_102": 0.289217832863587, "D_103": 1.0056231504565114, "D_104": 0.9613147105437548, "D_105": 0.1697762859187989, "D_106": "", "D_107": 0.3415914097814573, "B_36": 0.0014437035216303, "B_37": 0.0269399028855463, "R_26": 0.1079921756486303, "R_27": 0.0102809017375042, "B_38": 2.0, "D_108": "", "D_109": 0.0045981590747289, "D_110": "", "D_111": "", "B_39": "", "D_112": 0.0126469786018308, "B_40": 0.111658105064575, "S_27": 0.0085330483574145, "D_113": 0.6060588458397328, "D_114": 0.0, "D_115": 0.0543636921559064, "D_116": 0.0, "D_117": 3.0, "D_118": 0.1168077296764655, "D_119": 0.1096212138082288, "D_120": 0.0, "D_121": 0.650981600072707, "D_122": 0.146803227388556, "D_123": 0.0011049696432874, "D_124": 0.8183435054999706, "D_125": 0.000647677346751, "D_126": 1.0, "D_127": 5.266267486242482e-06, "D_128": 0.0029830598258818, "D_129": 0.007395236340952, "B_41": 0.0031757932139252, "B_42": "", "D_130": 1.0020848849400965, "D_131": 0.0061371572650052, "D_132": "", "D_133": 0.0018016269009619, "R_28": 0.0021418392238124, "D_134": "", "D_135": "", "D_136": "", "D_137": "", "D_138": "", "D_139": 1.0080621413676547, "D_140": 0.0035948604672395, "D_141": 0.8744796412184572, "D_142": 0.0901836791309312, "D_143": 1.0018106904900153, "D_144": 0.0044457500675465, "D_145": 0.3653796067325561}'}

In [114]:
param_data = json.loads(params['data'])
param_data

{'Unnamed: 0': 0,
 'customer_ID': '6ba461c93869797c49b0f34c29274e50915466eda02a82fde4aa2c73c3924339',
 'S_2': '2017-04-29',
 'P_2': 0.5243904931830153,
 'D_39': 0.3313523183745179,
 'B_1': 0.0226474075652035,
 'B_2': 1.0098138176705274,
 'R_1': 0.0094418612623092,
 'S_3': 0.3013753140016364,
 'D_41': 0.0078785629732383,
 'B_3': 0.0258205059627975,
 'D_42': 0.1442666865165377,
 'D_43': 0.2719021428514478,
 'D_44': '',
 'B_4': 0.0283137155569896,
 'D_45': 0.0181600179345101,
 'B_5': 0.042604957206283,
 'R_2': 0.0076086225667935,
 'D_46': 0.4423322496494613,
 'D_47': 0.5640947570546344,
 'D_48': '',
 'D_49': '',
 'B_6': 0.1141169198300304,
 'B_7': 0.0364595248656915,
 'B_8': 1.001206164416357,
 'D_50': '',
 'D_51': 0.0055727585123258,
 'B_9': 0.2995098902026097,
 'R_3': 0.5078069824461213,
 'D_52': 0.0065321521685339,
 'P_3': 0.9704147394434446,
 'B_10': 0.1931363807984167,
 'D_53': '',
 'S_5': 0.0497382032113571,
 'B_11': 0.0170887078387576,
 'S_6': 6.264821241336181e-06,
 'D_54': 1.003239737456082,
 'R_4': 0.0097192267864564,
 'S_7': 0.5836650003043637,
 'B_12': 0.0279422840289572,
 'S_8': 0.4724606934230521,
 'D_55': 0.3718658693500563,
 'D_56': '',
 'B_13': 0.0229769009343403,
 'R_5': 0.0024600658719739,
 'D_58': 0.092685414392393,
 'S_9': '',
 'B_14': 0.0187415315595689,
 'D_59': 0.2725730447049424,
 'D_60': 0.5128522688445263,
 'D_61': 0.996966160590678,
 'B_15': 0.008916801024969,
 'S_11': 0.2839718258314885,
 'D_62': 0.0063765535043084,
 'D_63': 'CO',
 'D_64': 'U',
 'D_65': 0.0082769054925904,
 'B_16': 0.3406488182369175,
 'B_17': 0.009998703087497,
 'B_18': 0.6902283738451007,
 'B_19': 0.0081695078433936,
 'D_66': '',
 'B_20': 0.0006330919917411,
 'D_68': 3.0,
 'S_12': 0.1916605915252538,
 'R_6': 0.0080456630109759,
 'S_13': 0.0018278306292617,
 'B_21': 0.0013618570248982,
 'D_69': 0.0985397767929114,
 'B_22': 0.0072234345795886,
 'D_70': 0.0090138733828583,
 'D_71': 0.0069688305279365,
 'D_72': 0.341570684555522,
 'S_15': 0.2066711654452798,
 'B_23': 0.0211564693339486,
 'D_73': '',
 'P_4': 0.9268010960381086,
 'D_74': 0.0806280135617195,
 'D_75': 0.0729107856856167,
 'D_76': '',
 'B_24': 0.0007743527406967,
 'R_7': 0.0036305356399982,
 'D_77': '',
 'B_25': 0.0269237456259648,
 'B_26': 0.0020041265394678,
 'D_78': '',
 'D_79': 0.0019684030320729,
 'R_8': 0.0095986871190017,
 'R_9': '',
 'S_16': 0.0073472057447631,
 'D_80': 0.0046132681510072,
 'R_10': 0.0002366237215068,
 'R_11': 0.5030766236950268,
 'B_27': 0.0080865243484111,
 'D_81': 0.0016620748567789,
 'D_82': '',
 'S_17': 0.0080248355218849,
 'R_12': 1.0088355475409474,
 'B_28': 0.0174737864388395,
 'R_13': 0.005137948786245,
 'D_83': 1.0010212222511732,
 'R_14': 0.0097658691950037,
 'R_15': 0.007744656789712,
 'D_84': 0.0053338538809249,
 'R_16': 0.5068937771309112,
 'B_29': '',
 'B_30': 0.0,
 'S_18': 0.0025881480646735,
 'D_86': 0.0084592043500856,
 'D_87': '',
 'R_17': 0.0064107803599046,
 'R_18': 0.0021582068627253,
 'D_88': '',
 'B_31': 1,
 'S_19': 0.0036599241820819,
 'R_19': 0.0023951620876795,
 'B_32': 0.0058979996465047,
 'S_20': 0.0084387973217704,
 'R_20': 0.0072765937081887,
 'R_21': 0.0026307474714683,
 'B_33': 1.0042078645998118,
 'D_89': 0.0093799559198365,
 'R_22': 0.0032245356122126,
 'R_23': 0.0084210175139439,
 'D_91': 0.0021117280992512,
 'D_92': 0.0002813886044537,
 'D_93': 0.0064740428785274,
 'D_94': 0.0034891282055373,
 'R_24': 0.0074637673580497,
 'R_25': 8.514154457408552e-05,
 'D_96': 0.0022346601508937,
 'S_22': 0.9896390752145902,
 'S_23': 0.1321254122831956,
 'S_24': 0.9834439806950838,
 'S_25': 0.9738907537358952,
 'S_26': 0.0038862860431581,
 'D_102': 0.289217832863587,
 'D_103': 1.0056231504565114,
 'D_104': 0.9613147105437548,
 'D_105': 0.1697762859187989,
 'D_106': '',
 'D_107': 0.3415914097814573,
 'B_36': 0.0014437035216303,
 'B_37': 0.0269399028855463,
 'R_26': 0.1079921756486303,
 'R_27': 0.0102809017375042,
 'B_38': 2.0,
 'D_108': '',
 'D_109': 0.0045981590747289,
 'D_110': '',
 'D_111': '',
 'B_39': '',
 'D_112': 0.0126469786018308,
 'B_40': 0.111658105064575,
 'S_27': 0.0085330483574145,
 'D_113': 0.6060588458397328,
 'D_114': 0.0,
 'D_115': 0.0543636921559064,
 'D_116': 0.0,
 'D_117': 3.0,
 'D_118': 0.1168077296764655,
 'D_119': 0.1096212138082288,
 'D_120': 0.0,
 'D_121': 0.650981600072707,
 'D_122': 0.146803227388556,
 'D_123': 0.0011049696432874,
 'D_124': 0.8183435054999706,
 'D_125': 0.000647677346751,
 'D_126': 1.0,
 'D_127': 5.266267486242482e-06,
 'D_128': 0.0029830598258818,
 'D_129': 0.007395236340952,
 'B_41': 0.0031757932139252,
 'B_42': '',
 'D_130': 1.0020848849400965,
 'D_131': 0.0061371572650052,
 'D_132': '',
 'D_133': 0.0018016269009619,
 'R_28': 0.0021418392238124,
 'D_134': '',
 'D_135': '',
 'D_136': '',
 'D_137': '',
 'D_138': '',
 'D_139': 1.0080621413676547,
 'D_140': 0.0035948604672395,
 'D_141': 0.8744796412184572,
 'D_142': 0.0901836791309312,
 'D_143': 1.0018106904900153,
 'D_144': 0.0044457500675465,
 'D_145': 0.3653796067325561}

In [131]:
X_pred = pd.DataFrame(param_data,index=[0]).replace('',np.nan)
X_pred

,Unnamed: 0,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,0,6ba461c93869797c49b0f34c29274e50915466eda02a82...,2017-04-29,0.52439,0.331352,0.022647,1.009814,0.009442,0.301375,0.007879,...,NaN,NaN,NaN,1.008062,0.003595,0.87448,0.090184,1.001811,0.004446,0.36538

In [115]:
d = {"value1": 0, "value2": 3, "value3": 3}

In [117]:
p = {"data": json.dumps(d)}
p

{'data': '{"value1": 0, "value2": 3, "value3": 3}'}

In [120]:
def test(data):
    dict_data = json.loads(data['data'])
    return dict_data

In [122]:
test_d = test(p)

In [128]:
test_d

{'value1': 0, 'value2': 3, 'value3': 3}

In [126]:
X_pred = pd.DataFrame({'key':"2013-07-06 17:18:00",
                'pickup_datetime':'data',
                'pickup_longitude':0}, index=[0])

In [129]:
X_pred = pd.DataFrame(test_d,index=[0])
X_pred

   value1  value2  value3
0       0       3       3